#!/usr/bin/env ruby

require 'tempfile'
require 'fileutils'

def runzclzlib(str)
  file = Tempfile.new('zcl').path
  gzcc = File.join(EXAMPLEDIR, 'zlibsimple')
  gzcd = File.join(EXAMPLEDIR, 'unzlibsimple')
  IO.popen("#{gzcc} | #{gzcd} >#{file}", "wb") do |p|
    p.write(str)
    p.close_write
  end
  result = File.read(file)
  FileUtils.rm(file)
  unless result == str
    raise "String of length #{str.size} broke zlib compression"
  end
end

def runsysgzipzcl(str, gzipoption, zclcommand)
  file = Tempfile.new('zcl').path
  gzc = File.join(EXAMPLEDIR, zclcommand)
  IO.popen("gzip #{gzipoption} | #{gzc} >#{file}", "wb") do |p|
    p.write(str)
    p.close_write
  end
  result = File.read(file)
  FileUtils.rm(file)
  unless result == str
    raise "String of length #{str.size} broke #{zclcommand}"
  end
end

def runzclsysgzip(str, gzipoption, zclcommand)
  file = Tempfile.new('zcl').path
  gzc = File.join(EXAMPLEDIR, zclcommand)
  IO.popen("#{gzc} | gzip #{gzipoption} >#{file}", "wb") do |p|
    p.write(str)
    p.close_write
  end
  result = File.read(file)
  FileUtils.rm(file)
  unless result == str
    raise "String of length #{str.size} broke #{zclcommand}"
  end
end

def makeStringOfSizeAtLeast(n)
  str = ''
  i = 0
  step = 0
  while str.size < n
    str += "#{i} "
    i += step
    step += 1
  end
  str
end

def runtests()
  20.times do | pow |
    len = 2 ** pow
    str = makeStringOfSizeAtLeast(len-1)
    runzclsysgzip(str, '-d', 'gzipsimple')
    runsysgzipzcl(str, '-c', 'ungzipsimple')
    runzclzlib(str)
  end
end

TOPDIR=File.expand_path('../..', __FILE__)
EXAMPLEDIR=File.join(TOPDIR, 'examples')
unless File.exist?(File.join(EXAMPLEDIR, 'gzipsimple'))
  system("make -C #{EXAMPLEDIR}")
end

runtests
